[project]
name = "cs336_basics"
version = "1.0.3"
description = "CS336 Assignment 1"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.1", # tensor operations
    "einx>=0.3.0", # more general tensor operations
    "jaxtyping>=0.3.0", # type hints for pytorch/jax/numpy
    "numpy",
    "psutil>=6.1.1",
    "pytest>=8.3.4",
    "regex>=2024.11.6", # more powerful regex than the builtin `re` module
    "submitit>=1.5.2", # job submission for SLURM
    "tiktoken>=0.9.0",
    "tqdm>=4.67.1",
    "wandb>=0.19.7",
    "scalene>=1.5.53",
    "pandas>=2.3.1",
    "snakeviz>=2.2.2",
    "cppyy>=3.5.0",
]

# Add PyPI first so it's checked before ROCm index for non-PyTorch packages
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"

[tool.uv.sources]
torch = { index = "pytorch-cu129" }


[dependency-groups]
cpu = [
   "torch==2.8.0; sys_platform == 'linux' and platform_machine == 'x86_64'", # CUDA for x86_64 Linux only
]
cuda = [
   "torch==2.8.0+cu129; sys_platform == 'linux' and platform_machine == 'x86_64'", # CUDA for x86_64 Linux only
]
# rocm = [
#    "torch==2.8.0+rocm6.4; sys_platform == 'linux' and platform_machine == 'x86_64'", # ROCM
#    "torchvision==0.23.0+rocm6.4; sys_platform == 'linux' and platform_machine == 'x86_64'", # ROCM
# ]

[tool.setuptools.packages.find]
include = ["cs336_basics"]


[tool.uv]
package = true
python-preference = "managed"
index-strategy = "unsafe-best-match"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
addopts = "-s"


[tool.ruff]
line-length = 120

[tool.ruff.lint.extend-per-file-ignores]
# Also ignore `E402` in all `__init__.py` files.
"__init__.py" = ["E402", "F401", "F403", "E501"]

[tool.ruff.lint]
extend-select = ["UP"]
ignore = [
    "F722"
]
