services:
  cs336-dev:
    build:
      dockerfile: cuda/Dockerfile.cuda
    devices:
      - "/dev/sdf:/dev/sdf"
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]