services:
  cs336-dev:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.11"
    privileged: false
    volumes:
      - ..:/workspace
      - .uv-cache:/opt/uv-cache
      - .venv:/opt/venv
    working_dir: /workspace
    environment:
      - UV_CACHE_DIR=/opt/uv-cache
    env_file:
      - ./.env
    entrypoint:
    command: sleep infinity
    user: vscode
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:2222:2222"